version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      args:
        BASE_IMAGE: "quay.io/centos/centos:stream9"
    env_file: ./server/.env
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      args:
        BASE_IMAGE: "quay.io/centos/centos:stream9"
    environment:
      API_BASE_URL: http://backend:9000
    links:
      - backend:backend
    ports:
      - "8080:80"
