version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    env_file: ./server/.env
    volumes:
      - ./server/data/input/default:/server/data/input/default:ro
      - ./server/data/output/default:/server/data/output/default:ro
      - ./server/data/input/:/server/data/input/
      - ./server/data/output/:/server/data/output/
    ports:
      - "9000:9000"
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    environment:
      API_BASE_URL: http://backend:9000
    links:
      - backend:backend
    ports:
      - "3000:80"
