---
- name: Deploy {{ app }} with Docker.
  hosts: all
  become: yes
  become_method: sudo
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    DOCKER_BUILDKIT: 1
  vars:
    - app: gwas-target
    - app_folder: "{{ app }}"
    - datetime: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"
    - image_tier: "{{ (tier in ['prod', 'stage']) | ternary('release', 'development') }}"
    - image_repository: "{{ docker_registry }}/{{ app }}"
    - frontend_image: "{{ image_repository }}:{{ image_tier }}-frontend-{{ app_git_tag }}-{{ datetime }}"
    - backend_image: "{{ image_repository }}:{{ image_tier }}-backend-{{ app_git_tag }}-{{ datetime }}"
    - frontend_image_latest: "{{ image_repository }}:{{ image_tier }}-frontend-latest"
    - backend_image_latest: "{{ image_repository }}:{{ image_tier }}-backend-latest"
    - frontend_container: "{{ tier }}-{{ app }}-frontend"
    - backend_container: "{{ tier }}-{{ app }}-backend"
    - frontend_container_port: 80
    - backend_container_port: 9000
    - frontend_app_path: /
    - ecs_cpu_units: "0.5 vCPU"
    - ecs_memory_units: "1 GB"
    - ecs_worker_cpu_units: "16 vCPU"
    - ecs_worker_memory_units: "40 GB"
    - aws_region: us-east-1
    - aws_account_tier: "{{ (tier in ['prod', 'stage']) | ternary('prod', 'nonprod') }}"
    - s3_data_bucket: "nci-cbiit-dceg-data-{{ aws_account_tier }}"
    - parameter_path: "/analysistools/{{ tier }}/{{ app }}"
    - docker_buildkit: '{{ "0" if no_cache == "true" else "1" }}'
    - task_definition_template_path: "{{ workspace_folder }}/deployment/build-deploy/ecs-task-definitions/{{ app }}"
    - no_cache: "false"

  tasks:
    - name: Build and push Docker images
      block:
        - name: Retrieve AWS account id
          shell: aws sts get-caller-identity --query "Account" --output text
          register: aws_account_result

        - name: Retrieve parameters
          shell: "aws ssm get-parameters-by-path --path {{ parameter_path }} --output json"
          register: aws_parameters_result

        - set_fact:
            ecs_cluster_query: "Parameters[?Name==`{{ parameter_path }}/ecs_cluster`].Value"
            ecs_web_task_query: "Parameters[?Name==`{{ parameter_path }}/ecs_web_task`].Value"
            ecs_worker_task_query: "Parameters[?Name==`{{ parameter_path }}/ecs_worker_task`].Value"
            ecs_web_service_query: "Parameters[?Name==`{{ parameter_path }}/ecs_web_service`].Value"
            role_arn_query: "Parameters[?Name==`{{ parameter_path }}/role_arn`].Value"
            efs_filesystem_id_query: "Parameters[?Name==`{{ parameter_path }}/efs_filesystem_id`].Value"
            efs_access_point_id_query: "Parameters[?Name==`{{ parameter_path }}/efs_access_point_id`].Value"
            ga4_tag_query: "Parameters[?Name==`{{ parameter_path }}/gtag`].Value"

        - set_fact:
            docker_registry: "{{ aws_account_result.stdout }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
            ecs_cluster: "{{ aws_parameters_result.stdout | from_json | json_query(ecs_cluster_query) | first }}"
            ecs_web_task: "{{ aws_parameters_result.stdout | from_json | json_query(ecs_web_task_query) | first }}"
            ecs_worker_task: "{{ aws_parameters_result.stdout | from_json | json_query(ecs_worker_task_query) | first }}"
            ecs_web_service: "{{ aws_parameters_result.stdout | from_json | json_query(ecs_web_service_query) | first }}"
            role_arn: "{{ aws_parameters_result.stdout | from_json | json_query(role_arn_query) | first }}"
            efs_filesystem_id: "{{ aws_parameters_result.stdout | from_json | json_query(efs_filesystem_id_query) | first }}"
            efs_access_point_id: "{{ aws_parameters_result.stdout | from_json | json_query(efs_access_point_id_query) | first }}"
            ga4_tag: "{{ aws_parameters_result.stdout | from_json | json_query(ga4_tag_query) | first }}"

        - name: Login to Docker registry
          shell: aws ecr get-login-password | docker login --username AWS --password-stdin {{ docker_registry }}

        - name: Ensure folders exist on build host
          file:
            dest: "{{ item }}"
            state: directory
            owner: "{{ ncianalysis_user }}"
            group: "{{ ncianalysis_group }}"
          with_items:
            - "{{ docker_app_root }}"
            - "{{ docker_app_root }}/{{ docker_app_code_folder }}"
            - "{{ docker_app_root }}/ecs"

        - name: Copy app source to build host
          synchronize:
            src: "{{ workspace_folder }}/{{ app_folder }}/"
            dest: "{{ docker_app_root }}/{{ docker_app_code_folder }}"
            delete: yes

        # note: docker_image does not support buildkit, so we must build images manually
        - name: Build backend image {{ backend_image }}
          shell: >
            DOCKER_BUILDKIT={{ docker_buildkit }}; \
            docker build \
              --pull \
              -t {{ backend_image }} \
              -t {{ backend_image_latest }} \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              {{ '--no-cache' if no_cache == 'true' else '--cache-from ' + backend_image_latest }} \
              -f {{ docker_app_root }}/{{ docker_app_code_folder }}/docker/backend.dockerfile \
              {{ docker_app_root }}/{{ docker_app_code_folder }};

            docker push {{ backend_image }};
            docker push {{ backend_image_latest }};
          async: 10800
          poll: 5
          when: rebuild_backend_image == "true"

        # note: docker_image does not support buildkit, so we must build images manually
        - name: Build frontend image {{ frontend_image }}
          shell: >
            DOCKER_BUILDKIT={{ docker_buildkit }}; \
            docker build \
              --pull \
              -t {{ frontend_image }} \
              -t {{ frontend_image_latest }} \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              {{ '--no-cache' if no_cache == 'true' else '--cache-from ' + frontend_image_latest }} \
              --build-arg APP_PATH={{ frontend_app_path }} \
              --build-arg REACT_APP_GTAG={{ ga4_tag }} \
              --build-arg REACT_APP_VERSION={{ app_git_tag }} \
              -f {{ docker_app_root }}/{{ docker_app_code_folder }}/docker/frontend.dockerfile \
              {{ docker_app_root }}/{{ docker_app_code_folder }};

            docker push {{ frontend_image }};
            docker push {{ frontend_image_latest }};
          async: 10800
          poll: 5
          when: rebuild_frontend_image == "true"

        - name: Update web service task definition from template
          ansible.builtin.template:
            src: "{{ task_definition_template_path }}//web.yml"
            dest: "{{ docker_app_root }}/ecs/web.yml"

        - name: Update worker task definition from template
          ansible.builtin.template:
            src: "{{ task_definition_template_path }}/worker.yml"
            dest: "{{ docker_app_root }}/ecs/worker.yml"

        - name: Register web service task definition
          shell: "aws ecs register-task-definition --cli-input-yaml file://{{ docker_app_root }}/ecs/web.yml"

        - name: Register worker task definition
          shell: "aws ecs register-task-definition --cli-input-yaml file://{{ docker_app_root }}/ecs/worker.yml"

        - name: Deploy web service
          shell: >
            aws ecs update-service \
              --cluster {{ ecs_cluster }} \
              --service {{ ecs_web_service }} \
              --task-definition {{ ecs_web_task }} \
              --desired-count 1 \
              --force-new-deployment;

      when: inventory_hostname in groups["build"]
